chapter-2.md

Hashing floats is generally bad practice (values that compare equal can have multiple representations), and I removed support for it in `AutoHashMap` in https://github.com/ziglang/zig/commit/345cb3200c353d6fb7aeb0e058986d8ca59ced1e .

Change f32 hashmap keys to u32

---

chapter-3.md

There's a missing hyphen in `--single-threaded`.

Fix small typo in chapter 3

---

chapter-3.md

Changed ```--release-small``` to ```-O ReleaseSmall``` (and so on) according to new master syntax.

--release-small becomes -O ReleaseSmall

---

chapter-3.md

For the sake of consistency with the new command in master, change `macosx` to `macos` as the name of the target platform

Change macosx to macos

---

chapter-1.md

Previous language may imply Zig doesn't have C++ style vectors, when that functionality indeed exists in ArrayLists.
This confused me when I was looking for vectors in Zig, hope it doesn't bite anyone else! Feedback welcome

Point users to Arraylist in vector section (tiny change).

---

chapter-1.md

The data types introduced don't really belong in a section about value assignment. It'd be better, in my opinion, to have that sort of information in another section like Data Types, which would ideally come just before the Assignment section.
To be more in line with Zig's preference for `const` over `var`, the examples place `const` stuff before `var` stuff wherever applicable.

Make Assignment a bit more readable and concise

---

chapter-1.md

* ~Adds array length and array operator information as both are pretty useful to know.~
* Removes literal/`T{}` construction sentence as it doesn't really pertain to arrays specifically and I think it was slightly incorrect since arrays are literals and but are also constructed with the `T{}` syntax.

Update Arrays section

---

chapter-1.md

`GetBiggerInt` is returning a type, and so should be PascalCase.

Correct Casing for GetBiggerInt Example

---

chapter-3.md

Due to new Zig site, there is a need to change Zig targets support table link on Chapter 3 Cross Compilaton.

Change Zig targets support table link

---

chapter-0.md

Zig 0.8 release party `\_()_/`!!
I wasn't sure whether to remove the line about Zig 0.8 being unsupported, since for now it should be that everything in the guide works for 0.8, although I guess that might eventually begin to diverge as Zig progresses to 0.9.

Update latest major version of Zig to 0.8

---

chapter-4.md

A user thought they needed to mark their Zig wrapper function as `callconv(.C)` because they were calling into C from Zig. This meant they couldn't use error unions and it got confusing.

chapter-4: clarify callconv

---

chapter-1.md
chapter-5.md

There were just a couple "I" statements in the whole docs, so switch them to "we" or passive voice to be consistent with the rest of the voice.

Use "we" consistently

---

chapter-1.md

Hey I'm finally getting around to checking out Zig, and am reading through the docs and found some things confusing, so here's my attempt to make them better! My context is that I'm fairly experienced in a wide variety of languages, perhaps most relevantly C++ and a bit of Rust, so that's my reference point here.
Firstly, payload captures were mentioned a couple times before actually being explained, without actually explaining what they were. The first time they're mentioned, I added a brief explanation of what bit of code _is_ the payload capture and mentioned we'll go more in depth later, The second time they came up, I elaborated a bit more on what we're doing with them there.
It might make more sense to move the whole "Payload Capture" section up and talk about them earlier, before …

Chapter 1: Clarify some language around payload captures

---

chapter-1.md

#111 added some explanations of payload captures.
This PR improves upon than and
- adds a missing `of`
- removes an unnecessary `used`

Chapter 1: Improve phrasing of additional explanations of palyload captures

---

chapter-3.md

In both Zig `0.8` and `master` this didn't comply with the API.

Fix for adding the `table-helper` package in chapter 3 (Build system)

---

chapter-2.md

since std.AutoHashMap's Entry (at least as of 0.8, haven't checked before) is defined as
```zig
pub const Entry = struct {
key_ptr: *K,
value_ptr: *V,
};
```
To update the sum (`sum.x += entry.value.x;`) we actually need `sum.x += entry.value_ptr.x;`

Update chapter-2 AutoHashMap

---

chapter-0.md

It said, "The output should start with 0.8.0-dev." but it's 0.9 now. Maybe just give an example instead?

version change

---

chapter-5.md

On version 0.8.1, the function `cmp` should return `std.math.Order` instead of `bool`

Change return type for function `cmp`

---

chapter-2.md

Allocator usage was changed on [0.9.0](https://ziglang.org/download/0.9.0/release-notes.html#Allocgate)

Update to 0.9.0

---

chapter-2.md

This makes the case of centered formatting slightly more informative, as it exposes the tendency to center to the left of the middle when forced to format in an even number of positions.

centered formatting in even numberd positions

---

chapter-5.md

The example in chapter 5 didn't work because at some point PriorityQueue switched to 3 argument constructor.
I figured out the problem and got it working.

fix chapter-5 event loop example, so that it works with PriorityQueue from 0.9.1

---

chapter-2.md

This diff fixes a tiny typo in the "Random Numbers" section.
The sentence "_Here we create a new prng using a 64 bit random seed. a, b, c, and are given random values via this prng._" is missing the name of the **d** variable after the "_and_".

Fix typo in the Random Numbers section

---

chapter-3.md

Noticed this when reading the documentation this morning. Feel free to close if this is incorrect.

fix: remove extra dash from zig init-lib

---

chapter-3.md

Running `zig build` w/ version 0.9.1 puts the binary in `zig-out` not `zig-cache`, at least on my machine with default settings.

Update output directory.

---

chapter-2.md

Without this I get
```
Test [1/1] test.make dir... thread 34048 panic: attempt to unwrap error: FileBusy
C:\Users\sigod\AppData\Local\zig\lib\std\os\windows.zig:922:31: 0x7ff722d6aeea in DeleteFile (test.exe.obj)
.SHARING_VIOLATION => return error.FileBusy,
^
```

Chapter 2: Fix 'make dir' test

---

chapter-3.md

We mention that the destination can be overridden, so we should also have a line next to it which specifies how.

Add method to override dest dir for zig build

---

website/blog/a-guessing-game.md

Fixes the compiler error: 
error: no field named 'random' in struct 'rand.Xoshiro256'
Tested working on zig version: 0.12.0-dev

Update to prng.random()

---

website/docs/02-standard-library/02-arraylist.mdx

I assume the lowercase 'L' in the 'Arraylist' header was a mistake

Fix case typo 'Arraylist' to 'ArrayList'

---

website/docs/01-language-basics/10-runtime-safety.mdx
website/docs/01-language-basics/11-pointers.mdx

Use CodeBlock to simplify code copying.

Update 10-runtime-safety.mdx and 11-pointers.mdx

---

website/versioned_docs/version-0.11/03-build-system/07-modules.md

No longer maintained, apparently.

`gyro` is in public archive now

---

website/blog/fahrenheit-to-celsius.md

As explained on the for-loop guide in zig.guide here - https://zig.guide/language-basics/for-loops/,
To capture the index, we also need to initialize the variable for index with 0 using `0..` syntax. This PR fixes that syntax typo.

fix: For-loop syntax in fahrenheit-to-celsius post

---

.gitignore

This is needed per this recent change: https://ziglang.org/download/0.13.0/release-notes.html#codezig-cachecode-renamed-to-codezig-cachecode

Add .zig-cache to gitignore

---

website/versioned_docs/version-0.12/02-standard-library/03-filesystem.mdx

This is the first time this feature is used in the guide, I believe, so explicitly introduce it.

Update 03-filesystem.mdx - introduce first use of auto-Enum scope

---

website/versioned_docs/version-0.13/01-language-basics/03-if.mdx

The current link yields a "Declaration not found" message.

Fix broken link

---

website/versioned_docs/version-0.13/01-language-basics/11-pointers.mdx
website/versioned_docs/version-0.14/01-language-basics/11-pointers.mdx

Fix guide for versions 0.14 & 0.13
Fix typo in code snippet. Discarding the variable should be `_ = &y;` instead of `_ = y;`.
Replace `var x: u16 = 0;` with `var x: u16 = 5; x -= 5;`. Else the compiler complains with `error: local variable is never mutated`. The updated example also highlights that the compiler is able to detect the value of x is not 0 after a mutation.
Note that `const x: u16 = 0` would have resulted in a different error message instead of `panic: cast causes pointer to be null`. 
resolves: https://github.com/Sobeston/zig.guide/issues/275

Fix code snippet to discard a pointer in "naughty pointer"

---

website/versioned_docs/version-0.13/01-language-basics/03-if.mdx
website/versioned_docs/version-0.14/01-language-basics/03-if.mdx

Since there is a dedicated page on running tests (https://zig.guide/getting-started/running-tests), the if expressions page doesn't need to "introduce testing".

Remove test summary from 'If Expressions' page.

---

website/versioned_docs/version-0.13/00-getting-started/02-installation.mdx

Noticed docs for 0.13.0 still show 0.12.0 when running `zig version`

Display correct version number (0.13.0) in 02-installation.mdx

---

website/versioned_docs/version-0.13/01-language-basics/07-defer.mdx

probably upon is more intuitive than while here. I don't know zig enough to say that "after" would be even better.

say "defer is executed upon exiting block" in Update 07-defer.mdx

---

website/versioned_docs/version-0.14/02-standard-library/07-random-numbers.mdx
website/versioned_docs/version-0.14/02-standard-library/07.random-numbers.zig

`rand` changed to `Random` as of https://github.com/ziglang/zig/pull/18867

rand to Random in 0.14 versioned docs

---

website/versioned_docs/version-0.11/01-language-basics/24-comptime.md
website/versioned_docs/version-0.12/01-language-basics/24-comptime.mdx

The current text and link present on chapter 24 is trying to link to a dead link and a deprecated type. Specifically, https://ziglang.org/documentation/master/std/#std;builtin.TypeInfo. That type has been deprecated since ziglang/zig@48bec903c2ee423170a13cce41edc755e6468e37 in favor of [std.builtin.Type](https://ziglang.org/documentation/master/std/#std.builtin.Type)

Fix `TypeInfo` link and name on chapter 24 - comptime

---

website/versioned_docs/version-0.11/01-language-basics/03-if.mdx
website/versioned_docs/version-0.12/01-language-basics/03-if.mdx
website/versioned_docs/version-0.13/01-language-basics/03-if.mdx
website/versioned_docs/version-0.14/01-language-basics/03-if.mdx

Since there is no participation note about a local hot reloadable dev server I just expect that this is being displayed as one would expect it. Haven't used mdx before, more of a markdown guy :P

01-if.mdx - add a hint that ternary operators don't exist in zig.
